version: '3.3'

services:

  academi-item-service:
    image: sever3d/academichain-item-service
    ports:
      - "9092:9092"
    environment:
      - POSTGRESHOST=${POSTGRESHOST}
      - POSTGRESPORT=${POSTGRESPORT}
      - POSTGRESUSER=${POSTGRESUSER}
      - POSTGRESPASSWORD=${POSTGRESPASSWORD}
      - POSTGRESDB=${POSTGRESDB}
      - CORE_SERVICE_URL=${CORE_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

    depends_on:
      - items-database-migrations
    networks:
      - msc


  items-database-migrations:
    image: "liquibase/liquibase:4.15.0"
    volumes:
      - ./db/changelog:/liquibase/changelog
      - ./db/sql:/liquibase/sql
    command:
      - "--url=jdbc:postgresql://postgres:5432/${POSTGRESDB}"
      - "--username=${POSTGRESUSER}"
      - "--password=${POSTGRESPASSWORD}"
      - "--changeLogFile=changelog/db.changelog-main.yml"
      - "--liquibaseSchemaName=items"
      - "update"
    networks:
      - msc

networks:
  msc:
    name: msc-localdev_msc
    driver: bridge
    external: true
